Support post auth
nsqio/nsq pull request #1487
Opened 2024-04-22 15:25 UTC by danrjohnson

This adds support for POST based authentication in addition to GET based authentication.

As described in https://github.com/nsqio/nsq/issues/1486, the default behavior of nsqd to to propagate upward any errors from `net/http` clients which leads to Secret's leakage if the authentication server is unavailble.

2024-04-22 15:25 UTC, danrjohnson commented
ready for review

2024-04-22 15:27 UTC, danrjohnson commented
I am curious for folks feedback on if we should make `application/json` POST requests or typical POST form behavior. Would love thoughts and happy to make a change here.

2024-04-28 18:40 UTC, mreiferson requested changes
Thanks for submitting this, just a few changes...

2024-04-28 18:40 UTC, mreiferson commented on internal/auth/authorizations.go
> +	clientTLSConfig *tls.Config, connectTimeout time.Duration, requestTimeout time.Duration, httpRequestType string) (*State, error) {
nit: let's keep the naming consistent... `httpRequestMethod`

2024-04-28 18:40 UTC, mreiferson commented on internal/http_api/api_request.go
> +	req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
To your comment on the PR, I think the body should be JSON encoded.

2024-04-28 18:40 UTC, mreiferson commented on apps/nsqd/options.go
> +	flagSet.String("auth-http-request-method", opts.AuthHTTPRequestMethod, "HTTP method to use for auth server requests")
Let's validate the input to `("get", "post")` in https://github.com/nsqio/nsq/blob/master/nsqd/nsqd.go#L77

2024-04-29 15:30 UTC, danrjohnson commented
@mreiferson Updated per your feedback! Thanks!

2024-05-12 10:14 UTC, mreiferson approved these changes
LGTM, thanks!

2024-05-12 10:25 UTC, mreiferson commented
(I did some minor function renaming and squashed/renamed the commit for merge...)

2024-05-12 10:39 UTC, merged